### ISSUE TITLE
Uncompleted code

### ISSUE THREAD

**Issue by linlin123git** [TAMU-VITA/ATMC#1]
Hi,

When I tried to run the codes, some modules seem to be uncompleted yet. 

python mnist/train_proj_admm_quant.py

Error message:
from super_module.super_class import Linear_QuantForward, Conv2d_QuantForward
ImportError: cannot import name 'Linear_QuantForward'

ImportError: No module named 'util_unnormalize'

I searched the repository but cannot find these modules. Can you please check it?

Many thanks.

**Comment by shupenggui** [comment]
Hi,

Thanks for pointing out the problem. We have cleaned the repo again and remove the dependency on Linear_QuantForward, Conv2d_QuantForward. Please try to pull and run it again.
